stages:
  - linting
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: linting
  artifacts:
    paths: [gl-code-quality-report.json]

code_quality_html:
  stage: linting
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

ruff:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff --format=gitlab .
