include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - lint
  - quality
  - build
  - test

ruff:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff --format=gitlab . > gl-code-quality-report.json
  allow_failure: true
  artifacts:
    when: always
    expire_in: 14 days
    reports:
      codequality: gl-code-quality-report.json

code_quality:    
  stage: quality
  artifacts:
    expire_in: 14 days
    paths: [gl-code-quality-report.json]

code_quality_html:
  stage: quality
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    expire_in: 14 days
    paths: [gl-code-quality-report.html]

mypy:
  stage: quality
  image: python:3.10-slim-buster
  before_script:
    - pip install poetry 
    - poetry config virtualenvs.create false
    - poetry install --only mypy
  script:
    - poetry run sh -lic "(mypy --config-file mypy.ini --no-error-summary . | mypy-gitlab-code-quality > gl-code-quality-report.json) || true"
  artifacts:
    when: always
    expire_in: 14 days
    reports:
      codequality: gl-code-quality-report.json

build-standalone:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  befire_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -f deploy/standalone.dockerfile .
    - docker push $IMAGE_TAG